### PR TITLE
Configure ports using a common configuration class instead of a hard-coded configuration

### PR DESCRIPTION
**Pull request by dengliming**

### CODE REVIEW

**Comment by wu-sheng** [comment]
From codes level, it should be fine to provide config. Could you share why you need this?

**Comment by dengliming** [comment]
> From codes level, it should be fine to provide config. Could you share why you need this?

Thanks for quick reply. I found that these two places can share the port configuration.
```
        NettyServerBuilder.forAddress(LocalAddress.ANY)
                          .forPort(19876)
```
org.apache.skywalking.plugin.test.mockcollector.service.GrpcAddressHttpService#doPost
 ```
JsonArray jsonArray = new JsonArray();
        jsonArray.add(ConfigReader.getGrpcBindHost() + ":" + ConfigReader.getGrpcBindPort());
```
And just a little advice. I can turn it off if it doesn't make sense.

**Comment by wu-sheng** [comment]
It is fine. I just wonder whether there is any issue locally. Let's wait @dmsolr confirmation. He is the project lead.

**Comment by dmsolr** [comment]
Sorry, I am so late. 
It is harmless. I don't know whether we need it. In my mind, we don't.
However, we can accept this PR if you need it.

**Pull request closed without merging**
