### PR TITLE
Add logging mock and validation.

### PR DESCRIPTION
**Pull request by jmjoy**

### CODE REVIEW

**Review by mrproliu — APPROVED** [review]
LGTM

**Comment by wu-sheng** [comment]
@jmjoy You should update plugin dev tool in the Java agent repo about this new validation.

**Comment by jmjoy** [comment]
> @jmjoy You should update plugin dev tool in the Java agent repo about this new validation.

Where's the location?

**Comment by jmjoy** [comment]
> The doc is hosted here, https://github.com/apache/skywalking-java/blob/main/docs/en/setup/service-agent/java-agent/Plugin-test.md
> 
> The website of latest is here, https://skywalking.apache.org/docs/skywalking-java/latest/en/setup/service-agent/java-agent/plugin-test/

Alright.

**Comment by jmjoy** [comment]
Refer: https://github.com/apache/skywalking-java/pull/294.

**Pull request merged**
